version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2345:2345"
    volumes:
      - ./backend:/usr/src/app
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
      POSTGRES_HOST: your_db_host
      PORT: 2345
