/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PabaA4LmFhV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"
import { Checkbox } from "@/components/ui/checkbox"
import { Button } from "@/components/ui/button"

export function SignUpPage() {
  return (
    (<div className="flex items-center justify-center min-h-screen bg-purple-100">
      <div className="w-full max-w-md p-8 space-y-6 bg-white rounded-lg shadow-lg">
        <h2 className="text-2xl font-bold text-center text-purple-700">Nome Completo</h2>
        <form className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="first-name">Nome Completo</Label>
            <Input id="first-name" placeholder="Nome Completo" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="cpf">CPF</Label>
            <Input id="cpf" placeholder="CPF" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" placeholder="Email" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Senha</Label>
            <Input id="password" type="password" placeholder="Senha" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="confirm-password">Confirme a sua senha</Label>
            <Input id="confirm-password" type="password" placeholder="Confirme a sua senha" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="gender">Sexo</Label>
            <RadioGroup defaultValue="Masculino">
              <div className="flex items-center space-x-4">
                <div className="flex items-center">
                  <RadioGroupItem id="male" value="male" />
                  <Label htmlFor="male" className="ml-2">
                    Masculino
                  </Label>
                </div>
                <div className="flex items-center">
                  <RadioGroupItem id="female" value="Feminino" />
                  <Label htmlFor="female" className="ml-2">
                    Feminino
                  </Label>
                </div>
              </div>
            </RadioGroup>
          </div>
          <div className="flex items-center space-x-2">
            <Checkbox id="terms" />
            <label htmlFor="terms" className="text-sm">
              Eu aceito os{" "}
              <a href="#" className="text-blue-500">
                Termos de Uso
              </a>{" "}
              &{" "}
              <a href="#" className="text-blue-500">
                Politicas de privacidade
              </a>
            </label>
          </div>
          <Button className="w-full bg-gray-500" disabled>
            Cadastrar
          </Button>
        </form>
        <p className="text-center">
          Já possui uma conta?{" "}
          <a href="#" className="text-blue-500">
            Clique Aqui
          </a>
        </p>
      </div>
    </div>)
  );
}
